### ISSUE TITLE
Compatibility with NC 30.

### ISSUE THREAD

**Issue by GVLLIFESTYLE** [nextcloud/twofactor_nextcloud_notification#902] opened 2024-10-03 04:58 UTC
The app does currently not work with NC 30.X.
It would be nice if someone could update it to make it work.

**Comment by nickvergessen** [comment] 2024-10-03 05:24
It's shipped with the server now. You can simply update.
- Duplicate of #895 and #900

**Closed** 2024-10-03 05:24 UTC
Labels: 0. Needs triage, enhancement
