### ISSUE TITLE
No registered devices and still sends notification

### ISSUE THREAD

**Issue by nexusxo** [nextcloud/twofactor_nextcloud_notification#922] opened 2024-11-13 05:21 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. When logged into the user account, enable the "Use registered device to login to account". The user has no other registered devices.
2. Logout of the portal
3. Try to log back in and it will still require you to approve the sign in request even if the user has no other devices registered with the account. So, they can't login and are now unable to login. I had to disable the app completely, so they could log back in.

### Expected behaviour
I would expect that if the user does not have any other registered devices to send a notification, it would allow them to bypass this step and just use the username/email and password to login.

### Actual behaviour
The user has no other devices registered to their account and with the app enabled, it still tries to send a notification to approve the login. But since there is no other device registered, nothing received the notification and the user cannot login.

### Server configuration

**Web server:** Apache

**Database:** Maria

**PHP version:** 8.2

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Hub 9 30.0.2

<details>
<summary>List of activated apps</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 3.0.0
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - forms: 4.3.3
  - groupfolders: 18.0.4
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - user_status: 1.10.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - welcome: 1.2.0
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - calendar: 5.0.1 (installed 5.0.1)
  - contacts: 6.1.1 (installed 6.1.1)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 1.20.0)
  - files_external: 1.22.0
  - firstrunwizard: 3.0.0 (installed 3.0.0)
  - geoblocker: 0.5.15 (installed 0.5.15)
  - nextcloud_announcements: 2.0.0 (installed 2.0.0)
  - photos: 3.0.2 (installed 3.0.2)
  - richdocuments: 8.5.2 (installed 8.5.2)
  - richdocumentscode: 24.4.902 (installed 24.4.902)
  - support: 2.0.0 (installed 2.0.0)
  - survey_client: 2.0.0 (installed 2.0.0)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0 (installed 4.0.0)
  - updatenotification: 1.20.0 (installed 1.20.0)
  - user_ldap: 1.21.0
  - weather_status: 1.10.0 (installed 1.10.0)

</details>

<details>
<summary>Nextcloud configuration</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": [
            "nextcloud.mylucidtech.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.2.2",
        "overwrite.cli.url": "https:\/\/nextcloud.mylucidtech.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "dashboard,files",
        "forbidden_filename_basenames": [
            "con",
            "prn",
            "aux",
            "nul",
            "com0",
            "com1",
            "com2",
            "com3",
            "com4",
            "com5",
            "com6",
            "com7",
            "com8",
            "com9",
            "com\u00b9",
            "com\u00b2",
            "com\u00b3",
            "lpt0",
            "lpt1",
            "lpt2",
            "lpt3",
            "lpt4",
            "lpt5",
            "lpt6",
            "lpt7",
            "lpt8",
            "lpt9",
            "lpt\u00b9",
            "lpt\u00b2",
            "lpt\u00b3"
        ],
        "forbidden_filename_characters": [
            "<",
            ">",
            ":",
            "\"",
            "|",
            "?",
            "*",
            "\\",
            "\/"
        ],
        "forbidden_filename_extensions": [
            " ",
            ".",
            ".filepart",
            ".part"
        ],
        "maintenance": false,
        "default_phone_region": "US",
        "maintenance_window_start": 1
    }
}

</details>

### Browser

**Browser name:** Chrome

**Browser version:** 130.0.6723.117 (Official Build) (64-bit)

**Operating system:** Windows 11 Pro

<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment] 2024-11-13 05:43
Despite the bad subject line, this is what #22 is about. I still don't have a perfect idea, how to solve this


Duplicate of #22

**Closed** 2024-11-13 05:43 UTC
Labels: 0. Needs triage, bug
